import {
  ReadFileArgsSchema,
  ReadMultipleFilesArgsSchema,
  WriteFileArgsSchema,
  EditFileArgsSchema,
  EditOperationType,
  GetFileInfoArgsSchema,
  MoveFileArgsSchema,
  DeleteFileArgsSchema,
  RenameFileArgsSchema,
  ReadFileArgs,
  ReadMultipleFilesArgs,
  WriteFileArgs,
  EditFileArgs,
  GetFileInfoArgs,
  MoveFileArgs,
  DeleteFileArgs,
  RenameFileArgs,
} from './file-operations.js';

import {
  CreateDirectoryArgsSchema,
  ListDirectoryArgsSchema,
  DirectoryTreeArgsSchema,
  DeleteDirectoryArgsSchema,
  CreateDirectoryArgs,
  ListDirectoryArgs,
  DirectoryTreeArgs,
  DeleteDirectoryArgs,
} from './directory-operations.js';

import {
  SearchFilesArgsSchema,
  FindFilesByExtensionArgsSchema,
  GetPermissionsArgsSchema,
  XmlToJsonArgsSchema,
  XmlToJsonStringArgsSchema,
  RegexSearchContentArgsSchema,
  XmlQueryArgsSchema,
  XmlStructureArgsSchema,
  SearchFilesArgs,
  FindFilesByExtensionArgs,
  GetPermissionsArgs,
  XmlToJsonArgs,
  XmlToJsonStringArgs,
  RegexSearchContentArgs,
  XmlQueryArgs,
  XmlStructureArgs,
} from './utility-operations.js';

import {
  JsonQueryArgsSchema,
  JsonFilterArgsSchema,
  JsonGetValueArgsSchema,
  JsonTransformArgsSchema,
  JsonStructureArgsSchema,
  JsonSampleArgsSchema,
  JsonValidateArgsSchema,
  JsonSearchKvArgsSchema,
  JsonQueryArgs,
  JsonFilterArgs,
  JsonGetValueArgs,
  JsonTransformArgs,
  JsonStructureArgs,
  JsonSampleArgs,
  JsonValidateArgs,
  JsonSearchKvArgs,
} from './json-operations.js';

export const toolSchemas = {
  read_file: ReadFileArgsSchema,
  read_multiple_files: ReadMultipleFilesArgsSchema,
  create_file: WriteFileArgsSchema,
  modify_file: WriteFileArgsSchema,
  edit_file: EditFileArgsSchema,
  create_directory: CreateDirectoryArgsSchema,
  list_directory: ListDirectoryArgsSchema,
  directory_tree: DirectoryTreeArgsSchema,
  delete_directory: DeleteDirectoryArgsSchema,
  search_files: SearchFilesArgsSchema,
  find_files_by_extension: FindFilesByExtensionArgsSchema,
  move_file: MoveFileArgsSchema,
  delete_file: DeleteFileArgsSchema,
  rename_file: RenameFileArgsSchema,
  get_file_info: GetFileInfoArgsSchema,
  get_permissions: GetPermissionsArgsSchema,
  xml_query: XmlQueryArgsSchema,
  xml_structure: XmlStructureArgsSchema,
  xml_to_json: XmlToJsonArgsSchema,
  xml_to_json_string: XmlToJsonStringArgsSchema,
  json_query: JsonQueryArgsSchema,
  json_structure: JsonStructureArgsSchema,
  json_filter: JsonFilterArgsSchema,
  json_get_value: JsonGetValueArgsSchema,
  json_transform: JsonTransformArgsSchema,
  json_sample: JsonSampleArgsSchema,
  json_validate: JsonValidateArgsSchema,
  json_search_kv: JsonSearchKvArgsSchema,
  regex_search_content: RegexSearchContentArgsSchema,
} as const;

export type {
  ReadFileArgs,
  ReadMultipleFilesArgs,
  WriteFileArgs,
  EditFileArgs,
  EditOperationType,
  GetFileInfoArgs,
  MoveFileArgs,
  DeleteFileArgs,
  RenameFileArgs,
  CreateDirectoryArgs,
  ListDirectoryArgs,
  DirectoryTreeArgs,
  DeleteDirectoryArgs,
  SearchFilesArgs,
  FindFilesByExtensionArgs,
  GetPermissionsArgs,
  XmlToJsonArgs,
  XmlToJsonStringArgs,
  RegexSearchContentArgs,
  XmlQueryArgs,
  XmlStructureArgs,
  JsonQueryArgs,
  JsonFilterArgs,
  JsonGetValueArgs,
  JsonTransformArgs,
  JsonStructureArgs,
  JsonSampleArgs,
  JsonValidateArgs,
  JsonSearchKvArgs,
};
